### ISSUE TITLE
Error: environment ".venv" not found

### ISSUE THREAD

**Issue by michox** [mme/langforge#1]
When trying to create a new app from powershell and hitting y on the virtual environment, the environment is created, however, then the error `environment ".venv" not found` occurs and no further files are created.

**Comment by mme** [comment]
Thanks for reporting! 

I must admit I did not test on Windows yet. 

Possibly it does not like the dot in the filename.

**Comment by mme** [comment]
@michox should work with the latest release.

Can you try again?

`pip3 install langforge-ai --upgrade`

**Comment by colinux-phd** [comment]
Hi, your project is really very interesting (I'm a fan of Jupyter ecosystem). Unfortunately something goes wrong running at present (i.e. the installed version of jupyterlab is 4.x but probably langforge requires jupyterlab v3, and so on respect to jupyter-server version...). Have you a langforge running instance / install from which create a requirements.txt (with pip freeze)?
Should be very useful to fix errors due to a lot new versions of python packages...

Thanks in advance!
J
